---
title: "ATAC"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

library(limma)
library(dplyr)
library(DT)
library(GenomicRanges)
library(tidyr)
library(pheatmap)
library(DESeq2)
library(BSgenome.Mmusculus.UCSC.mm10)
library(tracktables)
library(Rsubread)
library(clusterProfiler)
library(enrichplot)
library(ChIPseeker)
library(org.Mm.eg.db)
library(TxDb.Mmusculus.UCSC.mm10.knownGene)




filePath <- "~/Documents/macs2.Rep-SPMR/bed/"
sampleNames <- c("AC12","AC34")
peaks <- sapply(sampleNames, function(x) read.csv(file=paste0(filePath, x, "_peaks.narrowPeak"), header=T, sep="\t"), simplify=F)

filePath <- "~/Documents/macs2.Rep-SPMR/bed/"
sampleNames <- c("AC12","AC34")
peaks_1 <- sapply(sampleNames, function(x) read.csv(file=paste0(filePath, x, "_peaks-2.narrowPeak"), header=T, sep="."), simplify=F)







myPeaks <- lapply(peaks, ChIPQC:::GetGRanges, simple = TRUE)

#names(myPeaks) <- c("SEEM4P","SEEM2P","SEDM2P","PERKi4P","PERKi2P")

names(myPeaks) <- c("SEEM4P","SEEM2P")

#Group=factor(c("SEEM4P","SEEM2P","SEDM2P","PERKi4P","PERKi2P"))

Group=factor(c("SEEM4P","SEEM2P"))

myGRangesList<-GRangesList(myPeaks)   

reduced <- reduce(unlist(myGRangesList))
consensusIDs <- paste0("consensus_", seq(1, length(reduced)))
mcols(reduced) <- do.call(cbind, lapply(myGRangesList, function(x) (reduced %over% x) + 0))
reducedConsensus <- reduced
mcols(reducedConsensus) <- cbind(as.data.frame(mcols(reducedConsensus)), consensusIDs)
consensusIDs <- paste0("consensus_", seq(1, length(reducedConsensus)))
reducedConsensus








myPlot <- as.data.frame(elementMetadata(reducedConsensus)) %>% dplyr::select(-consensusIDs) %>% 
    as.matrix %>% t %>% prcomp %>% .$x %>% data.frame %>% mutate(Samples = rownames(.)) %>% 
    mutate(Group = gsub("_\\d", "", Samples)) %>% ggplot(aes(x = PC1, y = PC2, 
    colour = Group)) + geom_point(size = 5)

myPlot




occurrences <- elementMetadata(reducedConsensus) %>% as.data.frame %>% dplyr::select(-consensusIDs) %>% 
    rowSums

table(occurrences) %>% rev %>% cumsum


consensusToCount <- reducedConsensus[occurrences >= 2, ]

consensusToCount



filePath <- "~/Documents/macs2.Rep-SPMR/bed/"
sampleNames <- c("AC12","AC34")
bamsToCount<- c("AC12.bam","AC34.bam")

# indexBam(bamsToCount)
regionsToCount <- data.frame(GeneID = paste("ID", seqnames(consensusToCount), 
    start(consensusToCount), end(consensusToCount), sep = "_"), Chr = seqnames(consensusToCount), 
    Start = start(consensusToCount), End = end(consensusToCount), Strand = strand(consensusToCount))
fcResults <- featureCounts(files=bamsToCount,annot.ext=regionsToCount,isPairedEnd = FALSE,countMultiMappingReads = FALSE,maxFragLength=100)


myCounts <- fcResults$counts
colnames(myCounts) <- c("AC12","AC34")
save(myCounts, file = "countsFromATAC.RData")

myCounts=na.omit(myCounts)

pheatmap(myCounts[1:10,], scale='row', show_rownames = FALSE)





metaData <- data.frame(Group, row.names = colnames(myCounts))
atacDDS <- DESeqDataSetFromMatrix(myCounts, metaData, ~Group, rowRanges = consensusToCount)
atacDDS <- DESeq(atacDDS[-1])
atac_Rlog <- rlog(atacDDS)
plotPCA(atac_Rlog, intgroup = "Group", ntop = nrow(atac_Rlog))







HSCMinusCMP<- results(atacDDS, c("Group", "SEEM4P","SEEM2P"), format = "GRanges")
HSCMinusCMP<- HSCMinusCMP[order(HSCMinusCMP$pvalue)]
HSCMinusCMP



toOverLap <- promoters(TxDb.Mmusculus.UCSC.mm10.knownGene, 500, 500)
HSCMinusCMP <- HSCMinusCMP[(!is.na(HSCMinusCMP$padj) & HSCMinusCMP$pvalue < 0.05) & HSCMinusCMP %over% toOverLap]

makebedtable(HSCMinusCMP, "HSCMinusCMP.html", filePath)




anno_HSCMinusCMP <- annotatePeak(HSCMinusCMP, TxDb = TxDb.Mmusculus.UCSC.mm10.knownGene)


plotAnnoPie(anno_HSCMinusCMP)


go1 <- enrichGO(as.data.frame(as.GRanges(anno_HSCMinusCMP )[as.GRanges(anno_HSCMinusCMP )$log2FoldChange > 
    0])$geneId, OrgDb = "org.Mm.eg.db", ont = "BP", maxGSSize = 5000)
go2 <- enrichGO(as.data.frame(as.GRanges(anno_HSCMinusCMP )[as.GRanges(anno_HSCMinusCMP)$log2FoldChange < 
    0])$geneId, OrgDb = "org.Mm.eg.db", ont = "BP", maxGSSize = 5000)
    


head(go1, 10) %>% dplyr::select(ID, Description, pvalue, p.adjust) %>% datatable(elementId = "goEle1")
    
head(go2, 10) %>% dplyr::select(ID, Description, pvalue, p.adjust) %>% datatable(elementId = "goEle2")





anno_HSCMinusCMP_GRanges <- as.GRanges(anno_HSCMinusCMP)



anno_HSCMinusCMP_df <- as.data.frame(anno_HSCMinusCMP)
write.table(anno_HSCMinusCMP_df, "anno_HSCMinusCMP.csv", quote = FALSE, row.names = FALSE, sep = ",")












pheatmap(myCounts[1:100,], scale='row', show_rownames = FALSE)





library(stats)
correlationMatrix <- cor(myCounts[1:1000,1:4])


library(corrplot)
corrplot(correlationMatrix, order = 'hclust',  addrect = 6, addCoef.col = 'white', number.cex = 0.7) 


coldata=as.factor(sampleMetaData[1:2])

library(pheatmap)


pheatmap(correlationMatrix,cutree_cols = 2)






BiocManager::install("clusterProfiler", version = "3.8")
BiocManager::install("pathview")
BiocManager::install("enrichplot")

# we use ggplot2 to add x axis labels (ex: ridgeplot)
library(ggplot2)
\\






peakAnnoList <- lapply(myPeaks, annotatePeak, TxDb=TxDb.Mmusculus.UCSC.mm10.knownGene, tssRegion=c(-3000, 3000), verbose=FALSE)
names(peakAnnoList) <- basename(peakFiles)
ll
plotAnnoBar(peakAnnoList)
plotDistToTSS(peakAnnoList)









require(ChIPseeker)
require(rtracklayer)
require(TxDb.Mmusculus.UCSC.mm10.knownGene)
txdb <- TxDb.Mmusculus.UCSC.mm10.knownGene

# To import narrowPeak files
extraCols_narrowPeak <- c(signalValue = "numeric", pValue = "numeric",
                          qValue = "numeric", peak = "integer")

peakFiles <- list.files(pattern = ".narrowPeak", full.names = TRUE)
peakGRs <- lapply(peakFiles, import, format = "BED")


peaks <- sapply(peakFiles, function(x) read.csv(file=paste0(filePath, x, "_peaks.narrowpeak"), header=T, sep="\t"), simplify=F)


myPeaks <- lapply(peaks, ChIPQC:::GetGRanges, simple = TRUE)

peakAnnoList <- lapply(myGRangesList, annotatePeak, TxDb = TxDb.Mmusculus.UCSC.mm10.knownGene, tssRegion=c(-3000, 3000), verbose=FALSE)
names(peakAnnoList) <- basename(peakFiles)

plotAnnoBar(peakAnnoList)
plotDistToTSS(peakAnnoList)
